# Generated by Django 2.0 on 2020-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numerical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nName', models.CharField(max_length=20)),
                ('nSynopsis', models.CharField(max_length=200)),
                ('nIntroduce', models.TextField(max_length=2000)),
                ('imgPath', models.CharField(max_length=20)),
            ],
        ),
    ]
